// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syywyozsuxjdszggsxvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eXd5b3pzdXhqZHN6Z2dzeHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTQxMjAsImV4cCI6MjA2MDE5MDEyMH0.dfvs-F2fW5NhUpDtSBDexErjXOY2iNdUK4z09lL5N5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);